version: "3.5"

services:
    nexus:
        image: sonatype/nexus3:3.8.0
        volumes:
            - "nexus-data:/sonatype-work"
        ports:
            - "8081:8081"
        networks:
            - devops-internal

volumes:
    nexus-data: {}

networks:
  devops-internal:
    name: devops-internal
